openapi: 3.0.1
info:
  title: SmartVista RESTful API
  version: 1.0.0
servers:
  - url: 'https://localhost:7001/sv/rest'
  - url: 'http://localhost:7001/sv/rest'
tags:
  - name: application
    description: Create internal entities and process it
    externalDocs:
      description: Find out more
      url: 'https://confluence.bpcbt.com/'
paths:
  /application:
    post:
      tags:
        - application
      summary: Process incoming applications
      requestBody:
        description: Application objects that needs to be processed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '200':
          description: Success or logical errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          description: Invalid application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
  '/application/{applicationId}':
    get:
      tags:
        - application
      summary: Get application by its ID
      description: Returns a single application
      operationId: getPetById
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '404':
          description: Application not found
components:
  schemas:
    Application:
      required:
        - agent_id
        - application_flow_id
        - application_type
        - customer
        - customer_type
        - institution_id
      type: object
      properties:
        application_type:
          type: string
          format: 'APTP[0-9A-Z]{1,4}'
          example: APTPISSA
        application_flow_id:
          type: integer
          example: 1001
        application_status:
          type: string
          format: 'APST[0-9A-Z]{1,4}'
          example: APST0006
        operator_id:
          type: string
          example: OPERATOR1
        institution_id:
          type: integer
          example: 1001
        agent_id:
          type: integer
          example: 10000001
        agent_number:
          type: string
          example: 10000001
        customer_type:
          type: string
          format: 'ENTT[0-9A-Z]{1,4}'
          example: ENTTPERS
        customer:
          type: array
          items:
            $ref: '#/components/schemas/Customer'
    Customer:
      required:
        - command
        - customer_number
        - nationality
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCREX
        customer_number:
          type: string
          example: 009302127
        customer_category:
          type: string
          format: 'CCTG[0-9A-Z]{1,4}'
          example: CCTGORDN
        customer_relation:
          type: string
          format: 'RSCB[0-9A-Z]{1,4}'
          example: RSCBEXTR
        resident:
          type: integer
          example: 1
        nationality:
          type: string
          format: '[A-Z]{3}'
          example: RUS
        employment_status:
          type: string
          format: 'CSES[0-9A-Z]{1,4}'
          example: CSESEMPL
        employment_period:
          type: string
          format: 'EMPR[0-9A-Z]{1,4}'
          example: EMPR0001
        residence_type:
          type: string
          format: 'REST[0-9A-Z]{1,4}'
          example: RESTRENT
        marital_status_date:
          type: string
          format: YYYY-MM-DD
          example: 2016-02-01T00:00:00.000Z
        number_of_children:
          type: string
          format: 'CHLD[0-9A-Z]{1,4}'
          example: CHLD0001
        contract:
          type: array
          items:
            $ref: '#/components/schemas/Contract'
        person:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        contact:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        address:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        notification:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
    Contract:
      required:
        - command
        - contract_number
        - contract_type
        - product_id
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCREX
        contract_type:
          type: string
          format: 'CNTP[0-9A-Z]{1,4}'
          example: CNTPBANK
        product_id:
          type: integer
          example: 1
        contract_number:
          type: string
          example: 9302127001
        start_date:
          type: string
          format: YYYY-MM-DD
          example: 2021-10-02T00:00:00.000Z
        end_date:
          type: string
          format: YYYY-MM-DD
          example: 2023-10-02T00:00:00.000Z
        card:
          type: array
          items:
            $ref: '#/components/schemas/Card'
        account:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        service:
          type: array
          items:
            $ref: '#/components/schemas/Service'
    Card:
      required:
        - card_type
        - category
        - command
      type: object
      properties:
        id:
          type: string
          example: card_1
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCREX
        delivery_agent_number:
          type: string
          example: 123
        card_type:
          type: integer
          example: 1004
        category:
          type: string
          format: 'CRCG[0-9A-Z]{1,4}'
          example: CRCG0800
        cardholder:
          type: array
          items:
            $ref: '#/components/schemas/Cardholder'
    Cardholder:
      required:
        - cardholder_number
        - command
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRPR
        cardholder_number:
          type: string
          example: CH_7
        cardholder_name:
          type: string
          example: PETROV ALEX
        cardholder_photo_file_name:
          type: string
          example: File_1.img
        cardholder_sign_file_name:
          type: string
          example: File_2.img
        notification:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        sec_word:
          type: object
          items:
            $ref: '#/components/schemas/Security'
        language_preference:
          type: object
          items:
            $ref: '#/components/schemas/Preference'
    Security:
      required:
        - secret_answer
        - secret_question
      type: object
      properties:
        secret_question:
          type: string
          format: 'SEQU[0-9A-Z]{1,4}'
          example: SEQUWORD
        secret_answer:
          type: string
          example: qwerty
    Preference:
      required:
        - command
        - preferred_lang
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRUP
        preferred_lang:
          type: string
          format: 'LANG[0-9A-Z]{1,4}'
          example: LANGENG
    Notification:
      required:
        - command
        - delivery_address
        - delivery_channel
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCREX
        delivery_channel:
          type: integer
          example: 3
        delivery_address:
          type: string
          example: 79161234567
        is_active:
          type: integer
          example: 1
    Address:
      required:
        - address_type
        - command
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRUP
        address_type:
          type: string
          format: 'ADTP[0-9A-Z]{1,4}'
          example: ADTPHOME
        address_name:
          type: array
          items:
            $ref: '#/components/schemas/AddressName'
    AddressName:
      required:
        - language
      type: object
      properties:
        language:
          type: string
          format: 'LANG[0-9A-Z]{1,4}'
          example: LANGENG
        region:
          type: string
          example: Moscow DC
        city:
          type: string
          example: Moscow
        street:
          type: string
          example: Tverskaya
        house:
          type: string
          example: 11
        apartment:
          type: string
          example: 120
    Contact:
      required:
        - command
        - contact_type
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRUP
        contact_type:
          type: string
          format: 'CNTT[0-9A-Z]{1,4}'
          example: CNTTPRMC
        preferred_lang:
          type: string
          format: 'LANG[0-9A-Z]{1,4}'
          example: LANGENG
        contact_data:
          type: array
          items:
            $ref: '#/components/schemas/ContactData'
    ContactData:
      required:
        - commun_address
        - commun_method
      type: object
      properties:
        commun_method:
          type: string
          format: 'CMNM[0-9A-Z]{1,4}'
          example: CMNM0001
        commun_address:
          type: string
          format: 'CNTT[0-9A-Z]{1,4}'
          example: 79161234511
    Person:
      required:
        - command
        - person_name
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRUP
        person_name:
          type: array
          items:
            $ref: '#/components/schemas/PersonName'
        identity_card:
          type: array
          items:
            $ref: '#/components/schemas/IdentityCard'
    Account:
      required:
        - account_number
        - account_type
        - command
        - currency
      type: object
      properties:
        id:
          type: string
          example: account_1
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCREX
        account_number:
          type: string
          example: 40817810100000780000
        currency:
          type: integer
          example: 643
        account_type:
          type: string
          format: 'ACTP[0-9A-Z]{1,4}'
          example: ACTP0100
        account_object:
          type: array
          items:
            $ref: '#/components/schemas/AccountObject'
    AccountObject:
      required:
        - account_link_flag
        - ref_id
      type: object
      properties:
        ref_id:
          type: string
          example: card_1
        account_link_flag:
          type: integer
          example: 1
    PersonName:
      required:
        - language
      type: object
      properties:
        language:
          type: string
          format: 'LANG[0-9A-Z]{1,4}'
          example: LANGENG
        first_name:
          type: string
          example: Ivan
        second_name:
          type: string
          example: Ivanovich
        surname:
          type: string
          example: Ivanov
    IdentityCard:
      required:
        - command
        - id_number
        - id_type
      type: object
      properties:
        command:
          type: string
          format: 'CMMD[0-9A-Z]{1,4}'
          example: CMMDCRUP
        id_type:
          type: string
          format: 'IDTP[0-9A-Z]{1,4}'
          example: IDTP0001
        id_series:
          type: string
          example: 4412
        id_number:
          type: string
          example: 555555
    Service:
      required:
        - service_object
        - value
      type: object
      properties:
        value:
          type: integer
          example: 10002157
        service_object:
          type: array
          items:
            $ref: '#/components/schemas/ServiceObject'
    ServiceObject:
      required:
        - ref_id
      type: object
      properties:
        ref_id:
          type: integer
          example: 10002157
        start_date:
          type: string
          format: YYYY-MM-DD
          example: 2021-10-02T00:00:00.000Z
        end_date:
          type: string
          format: YYYY-MM-DD
          example: 2023-10-02T00:00:00.000Z
        attribute_num:
          type: array
          items:
            $ref: '#/components/schemas/AttributeNumber'
        attribute_char:
          type: array
          items:
            $ref: '#/components/schemas/AttributeChar'
        attribute_limit:
          type: array
          items:
            $ref: '#/components/schemas/AttributeLimit'
    AttributeNumber:
      required:
        - attribute_value_num
        - value
      type: object
      properties:
        value:
          type: integer
          example: 10002774
        attribute_value_num:
          type: integer
          example: 1000
    AttributeChar:
      required:
        - attribute_value_char
        - value
      type: object
      properties:
        value:
          type: integer
          example: 10002773
        attribute_value_char:
          type: string
          example: CRDP0002
    AttributeLimit:
      required:
        - limit_check_type
        - value
      type: object
      properties:
        value:
          type: integer
          example: 10003350
        limit_sum_value:
          type: integer
          example: 2000
        limit_check_type:
          type: string
          format: 'LCHT[0-9A-Z]{1,4}'
          example: LCHT0001
        currency:
          type: integer
          example: 643
        counter_algorithm:
          type: string
          format: 'ACCL[0-9A-Z]{1,4}'
          example: ACCL0001
    InvalidRequest:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
          example: 1623140259149
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        exception:
          type: string
          example: HttpMessageNotReadableException
        message:
          type: string
          example: 'JSON parse error: Unrecognized token'
        path:
          type: string
          example: /sv/rest/application
